[package]
name = "pls"
description = "`pls` is a prettier and powerful `ls` for the pros."
version = "0.0.0"

authors = ["Dhruv Bhanushali <hi@dhruvkb.dev>"]

license = "GPL-3.0-or-later"

homepage = "https://dhruvkb.github.io/pls"
repository = "https://github.com/dhruvkb/pls"
documentation = "https://dhruvkb.github.io/pls"
readme = "README.md"
exclude = [".github/", "/readme_assets", "/justfile", "/.gitignore"]

keywords = ["cli", "terminal", "posix", "ls"]
categories = ["command-line-utilities"]

edition = "2021"
rust-version = "1.70.0"

[[bin]]
name = "pls"

[dependencies]
clap = { version = "4.3.11", features = ["derive", "wrap_help"] }
colored = "2.0.0"
lazy_static = "1.4.0"
number_prefix = "0.4.0"
regex = { version = "1.8.4", default-features = false, features = ["std", "perf"] }
serde = { version = "1.0.164", features = ["derive"] }
unicode-segmentation = "1.10.1"
users = { version = "0.11.0", default-features = false, features = ["cache"] }

[profile.release]
# Reference: https://github.com/johnthagen/min-sized-rust
codegen-units = 1
panic = "abort"
lto = true
strip = true
