name: pls/setup-env
description: Setup environment for CI + CD jobs

inputs:
  rust_cache_key:
    description: The key to use to identify the Rust toolchain cache
    default: cargo
  rust_components:
    description: dtolnay/rust-toolchain#components
    required: false
  rust_target:
    description: dtolnay/rust-toolchain#target
    required: false

runs:
  using: composite
  steps:
    - name: Setup `just`
      uses: taiki-e/install-action@v2
      with:
        tool: just

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust_components }}
        target: ${{ inputs.rust_target }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key:
          ${{ runner.os }}-${{ inputs.rust_cache_key }}-${{
          hashFiles('**/Cargo.lock') }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable pnpm

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: .nvmrc
      env:
        COREPACK_INTEGRITY_KEYS: '{"npm":[{"expires":"2025-01-29T00:00:00.000Z","keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="},{"expires":null,"keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6Ya7W++7aUPzvMTrezH6Ycx3c+HOKYCcNGybJZSCJq/fd7Qa8uuAKtdIkUQtQiEKERhAmE5lMMJhP8OkDOa2g=="}]}'

    - name: Install Node.js dependencies
      shell: bash
      run: pnpm install
