$schema: http://json-schema.org/draft-07/schema
$id: https://dhruvkb.github.io/pls/schemas/pls_config.yml

title: "`pls` config"
description: "Schema of the `pls` config file"

type: object
additionalProperties: false
properties:
  node_specs:
    title: Node specs
    description: list of specs to configure how nodes are rendered

    type: array
    items:
      $ref: "#/$defs/node_spec"

  nerd_icons:
    title: Nerd Font icons
    description: mapping of icon names to Unicode code points for Nerd Font icons

    type: object
    properties: {}
    additionalProperties:
      type: string

  emoji_icons:
    title: Emoji icons
    description: mapping of icon names to emoji glyphs

    type: object
    properties: {}
    additionalProperties:
      type: string

$defs:
  ###################
  # Spec attributes #
  ###################
  name:
    title: Node name
    description: the complete name of the file, including the extension if any

    oneOf:
      - type: string
      - type: array
        items:
          type: string

  extension:
    title: Node extension
    description: the extension of the node, last segment when splitting the name at dots

    oneOf:
      - type: string
      - type: array
        items:
          type: string

  pattern:
    title: Node pattern
    description: a regex pattern compared against the node name from the start

    oneOf:
      - type: string
        format: regex
      - type: array
        items:
          type: string
          format: regex

  icon:
    title: Icon name
    description: the name of the icon to associate with the file

    type: string

  importance:
    title: Importance
    description: the relevance of a node to your workflow

    type: integer
    default: 0

  color:
    title: Text color
    description: the color in which to render the node name

    type: string
    oneOf:
      # standard color names
      - pattern: ^\w+$
      # rgb triplet
      - pattern: ^rgb\((\s?(1?[0-9]{1,2}|2[0-4][0-9]|25[0-5])\s?,){2}(\s?(1?[0-9]{1,2}|2[0-4][0-9]|25[0-5])\s?)\)$
      # 3 or 6 digit hex code
      - pattern: "^#([0-9a-f]{3}|[0-9a-f]{6})$"

  collapse:
    title: Collapse
    description: configures behaviour for collapsing an unimportant node

    type: object
    additionalProperties: false
    properties:
      name:
        $ref: "#/$defs/name"
      extension:
        $ref: "#/$defs/extension"

  #############
  # Node spec #
  #############
  node_spec:
    title: Node spec
    description: configures a rule to identify a node and set its appearance

    type: object
    additionalProperties: false
    properties:
      name:
        $ref: "#/$defs/name"
      extension:
        $ref: "#/$defs/extension"
      pattern:
        $ref: "#/$defs/pattern"

      icon:
        $ref: "#/$defs/icon"
      importance:
        $ref: "#/$defs/importance"
      color:
        $ref: "#/$defs/color"
      collapse:
        $ref: "#/$defs/collapse"

    oneOf:
      - required: [name]
      - required: [extension]
      - required: [pattern]

    dependencies:
      name:
        properties:
          collapse:
            required: [name]
            not:
              required: [extension]
      extension:
        properties:
          collapse:
            required: [extension]
            not:
              required: [name]
      pattern:
        properties:
          not:
            required: [collapse]
