icons:
  javascript: "󰌞" # nf-md-language_javascript
  typescript: "󰛦" # nf-md-language_typescript
specs:
  - pattern: \.ts$
    icons:
      - typescript
    style: rgb(49,120,198)
  - pattern: \.m?js$
    icons:
      - javascript
    style: rgb(247,223,30)
  - pattern: \.astro$
    icons:
      - rocket
    style: rgb(255,93,1)
  - pattern: ^package-lock\.json$
    icons:
      - package
  - pattern: ^pnpm-lock.yaml$
    icons:
      - lock
    importance: -1
    collapse:
      name: package.json
