name: Docs

on:
  push:
    branches:
    - docs
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: "docs"
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "npm"
        cache-dependency-path: "**/package-lock.json"

    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
        force_orphan: true
